version: '3'
services:
  zookernel:
    platform: linux/amd64
    image: ades:latest
    build: .
    ports:
      - "80:80"
    volumes:
      - ./assets/classic/main.cfg:/usr/lib/cgi-bin/main.cfg
      - ./assets/classic/oas.cfg:/usr/lib/cgi-bin/oas.cfg
      - ./src/zoo-services/assets/cookiecutter-templates:/tmp/cookiecutter-templates
      - ./src/zoo-services/assets/cookiecutter_config.yaml:/tmp/cookiecutter_config.yaml
      - ./src/zoo-services/services/DeployProcess.py:/usr/lib/cgi-bin/DeployProcess.py
      - ./src/zoo-services/services/DeployProcess.zcfg:/usr/lib/cgi-bin/DeployProcess.zcfg
      - ./src/zoo-services/services/GitService.py:/usr/lib/cgi-bin/GitService.py
      - ./src/zoo-services/services/GitService.zcfg:/usr/lib/cgi-bin/GitService.zcfg