version: '3'
services:
  zookernel:
    platform: linux/amd64
    image: ades:latest
    build: .
    ports:
      - "80:80"
    volumes:
      - ./assets/full/main.cfg:/usr/lib/cgi-bin/main.cfg
      - ./assets/full/oas.cfg:/usr/lib/cgi-bin/oas.cfg
      - ./assets/default.conf:/etc/apache2/sites-available/000-default.conf
      - ./assets/full/scripts/publish.py:/usr/lib/cgi-bin/publish.py
      - ./assets/full/scripts/subscriber.py:/usr/lib/cgi-bin/subscriber.py
      - ./src/zoo-services/assets/cookiecutter-templates:/usr/lib/cgi-bin/assets/cookiecutter-templates
      - ./src/zoo-services/assets/cookiecutter_config.yaml:/usr/lib/cgi-bin/assets/cookiecutter_config.yaml
      - ./src/zoo-services/services/DeployProcess.py:/usr/lib/cgi-bin/DeployProcess.py
      - ./src/zoo-services/services/DeployProcess.zcfg:/usr/lib/cgi-bin/DeployProcess.zcfg
      - ./src/zoo-services/assets/AdesService.py:/usr/lib/cgi-bin/AdesService.py
      - ./src/zoo-services/assets/AdesService.zcfg:/usr/lib/cgi-bin/AdesService.zcfg
      - ./src/zoo-services/assets/echo_service.py:/usr/lib/cgi-bin/echo_service
      - ./src/zoo-services/assets/echo.zcfg:/usr/lib/cgi-bin/echo.zcfg

    depends_on:
      - pgbouncer
      - redis
    environment:
      - ZOO_REDIS_HOST=redis
  websocketd:
    platform: linux/amd64
    build: ./assets/full/docker/websocketd
    depends_on:
      - redis
    ports:
      - 8888:8888
    environment:
      - ZOO_REDIS_HOST=redis
    volumes:
      - ./assets/full/scripts/subscriber.py:/shell.py
    command: ["--port=8888", "/shell.py"]
  pg:
    platform: linux/amd64
    image: postgres:9.6.18-alpine
    restart: always
    environment:
      POSTGRES_USER: zoo
      POSTGRES_PASSWORD: zoo
      POSTGRES_DB: zoo
    volumes:
      # Load the zoo kernel schema
      - ./assets/full/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
  pgbouncer:
    platform: linux/amd64
    image: edoburu/pgbouncer:1.8.1
    environment:
      DATABASE_URL: "postgres://zoo:zoo@pg/zoo"
      MAX_CLIENT_CONN: 1000
      MAX_DB_CONNECTIONS: 100
      DEFAULT_POOL_SIZE: 100
      POOL_MODE: transaction
    ports:
      - "5432:5432"
    depends_on:
      - pg
  redis:
    image: redis:6.0.9