apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o charts/ades/templates_kompose/
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: pgbouncer
  name: pgbouncer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pgbouncer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o charts/ades/templates_kompose/
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: pgbouncer
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: postgres://zoo:zoo@pg/zoo
            - name: DEFAULT_POOL_SIZE
              value: "100"
            - name: MAX_CLIENT_CONN
              value: "1000"
            - name: MAX_DB_CONNECTIONS
              value: "100"
            - name: POOL_MODE
              value: transaction
          image: edoburu/pgbouncer:1.8.1
          name: pgbouncer
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
