apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ades.fullname" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  maincfg: {{ tpl (.Files.Get .Values.zoo.kernel.maincfgtpl) . | quote }}
  oas: {{ tpl (.Files.Get .Values.zoo.kernel.oas) . | quote }}
  htaccess: {{ tpl (.Files.Get .Values.zoo.kernel.htaccess) . | quote }}

