apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ades.fullname" . }}-startup-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  startUp.sh: {{ tpl (.Files.Get .Values.zoo.openapi.startupsh) . | quote }}

