apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookernel
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "ades.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - env:
            - name: ZOO_REDIS_HOSTss
              value: redis
          image: ades:latest
          name: zookernel
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /usr/lib/cgi-bin/main.cfg
              name: zookernel-claim0
            - mountPath: /usr/lib/cgi-bin/oas.cfg
              name: zookernel-claim1
            - mountPath: /var/www/html/.htaccess
              name: zookernel-claim2
            - mountPath: /assets
              name: zookernel-claim3
            - mountPath: /tmp/cookiecutter_config.yaml
              name: zookernel-claim4
            - mountPath: /usr/lib/cgi-bin/DeployProcess.py
              name: zookernel-claim5
            - mountPath: /usr/lib/cgi-bin/DeployProcess.zcfg
              name: zookernel-claim6
            - mountPath: /usr/lib/cgi-bin/UndeployProcess.py
              name: zookernel-claim7
            - mountPath: /usr/lib/cgi-bin/UndeployProcess.zcfg
              name: zookernel-claim8
            - mountPath: /usr/lib/cgi-bin/deploy_util.py
              name: zookernel-claim9
            - mountPath: /usr/lib/cgi-bin/HelloPy.zcfg
              name: zookernel-claim10
            - mountPath: /usr/lib/cgi-bin/test_service.py
              name: zookernel-claim11
      restartPolicy: Always
      volumes:
        - name: zookernel-claim0
          persistentVolumeClaim:
            claimName: zookernel-claim0
status: {}
