name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sergeysova/jq-action@v2
      - name: Build Ades
        run: docker build . --tag ades:latest --no-cache
      - name: Run Ades
        run: docker-compose up -d
      - name: "Test1: List Services"
        run: curl http://localhost/ogc-api/processes | jq
      - name: "Test2: Deploy dnbr service"
        run: |
          curl --location --request POST 'http://localhost/ogc-api/processes/DeployProcess' \
              --header 'Content-Type: application/json' \
              --data-raw '{
                  "inputs": {
                      "applicationPackage": {
                          "mimeType": "application/cwl",
                          "value": {
                              "href": "https://raw.githubusercontent.com/EOEPCA/proc-ades/develop/test/sample_apps/dNBR/dNBR.cwl#dnbr"
                          }
                      }
                  },
                  "outputs": {
                      "deployResult": {
                          "format": {
                              "mediaType": "application/json"
                          },
                          "transmissionMode": "reference"
                      }
                  }
              }'
        